services:
  nuxt:
    tmpfs:
      # https://github.com/nuxt/nuxt/issues/13587#issuecomment-1451481510
      - /tmp
    ports:
      - "${NUXT_PORT:-3000}:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    working_dir: "/app"
    command: "sh -c 'pnpm install && pnpm dev'"
    env_file:
      - .env
volumes:
  node_modules:
